/** Declaration file generated by dts-gen */

declare const webpack_config: {
    devtool: string
    entry: {
        app: string[]
    }
    externals: {
        react: string
        'react-dom': string
    }
    mode: string
    module: {
        rules: {
            exclude: RegExp
            loader: string
            query: {
                configFileName: string
            }
            test: RegExp
        }[]
    }
    output: {
        devtoolModuleFilenameTemplate: string
        filename: string
        path: string
        publicPath: string
    }
    plugins: {
        addFileToAssets: any
        appendHash: any
        apply: any
        applyPluginsAsyncWaterfall: any
        createHtmlTag: any
        evaluateCompilationResult: any
        executeTemplate: any
        filterChunks: any
        generateHtmlTags: any
        getAssetFiles: any
        getFullTemplatePath: any
        getMetaTags: any
        getTemplateParameters: any
        htmlWebpackPluginAssets: any
        injectAssetsIntoHtml: any
        isHotUpdateCompilation: any
        options: {
            cache: boolean
            chunks: string
            chunksSortMode: string
            compile: boolean
            excludeChunks: any[]
            favicon: boolean
            filename: string
            hash: boolean
            inject: boolean
            meta: {}
            minify: boolean
            showErrors: boolean
            template: string
            templateParameters: any
            title: string
            xhtml: boolean
        }
        postProcessHtml: any
        sortChunks: any
    }[]
    resolve: {
        extensions: string[]
    }
}

export = webpack_config
